### PR TITLE
add different header to addGet,addDelete,addPost

### PR DESCRIPTION
**Pull request by colapiombo**
add diffrent header to addGet,addDelete,addPost

### CODE REVIEW

**Comment by zachborboa** [comment]
Hi. I think it's better to use `setHeader`outside of the `addGet`, `addDelete`, and `addPost` methods.

``` php
$headers = array(
    'Content-Type' => 'application/json',
    'X-CUSTOM-HEADER' => 'my-custom-header',
);

$multi_curl = new MultiCurl();

$multi_curl->beforeSend(function ($instance) use ($headers) {
    foreach ($headers as $key => $value) {
        $instance->setHeader($key, $value);
    }
});

$multi_curl->addGet('https://www.example.com/');
$multi_curl->addGet('https://www.example.org/');
$multi_curl->addGet('https://www.example.net/');

$multi_curl->start();
```

**Comment by colapiombo** [comment]
Hi , i think is not correct because in my case i need to send some user information by header, and with your system is impossibile because for all call is the same header

`$header = array(
            'Content-Type'=>'application/json; charset=UTF-8',
            'Accept'=>'application/json; charset=UTF-8',
            'API-KEY'=> firstUserKey
            'TOKEN'=>firstToken    );
$multi_curl->addGet('https://www.example.com/',null,$header);

$header = array(
            'Content-Type'=>'application/json; charset=UTF-8',
            'Accept'=>'application/json; charset=UTF-8',
            'API-KEY'=> SecondUserKey,
            'TOKEN'=>SecondToken);
$multi_curl->addGet('https://www.example.com/',null,$header);`

**Comment by zachborboa** [comment]
In that case you can save `$multi_curl->addGet()` to a variable.

``` php
$get = $multi_curl->addGet('https://www.example.com/');
$get->beforeSend(function ($instance) use ($headers) {
    foreach ($headers as $key => $value) {
        $instance->setHeader($key, $value);
    }
});
```

**Comment by colapiombo** [comment]
thank you ;)

**Pull request closed without merging**
